### PR TITLE
[#1060] Adjust docs/typings for initialFocus option

### LINKED ISSUE #1060: Adjust types to allow `initialFocus: () => undefined`
`initialFocus` can be `undefined`, in this case the first tabbable node will be focused. Also, we can pass a function returning an element. But we can't return undefined in that function (according to the types):

https://github.com/focus-trap/focus-trap/blob/94645ebfc34b8de6fbddc9ae5ea45127bd4ef90e/index.d.ts#L12

But according to the implementation, it actually works:

https://github.com/focus-trap/focus-trap/blob/94645ebfc34b8de6fbddc9ae5ea45127bd4ef90e/index.js#L270

https://github.com/focus-trap/focus-trap/blob/94645ebfc34b8de6fbddc9ae5ea45127bd4ef90e/index.js#L233-L267

So I suggest to adjust the types to allow `undefined` as a valid function return type.

### PR DESCRIPTION
**Pull request by stefcameron**
Fixes #1060

The option can _also_ be set to `undefined` or a function that returns `undefined`.

<details>
<summary>PR Checklist</summary>
<br/>

__Please leave this checklist in your PR.__

- Issue being fixed is referenced.
- Source changes maintain stated browser compatibility.
- Web APIs introduced have __deep__ browser coverage, including Safari (often very late to adopt new APIs).
- Includes updated docs demo bundle if source/docs code was changed (run `npm run demo-bundle` in your branch and include the `/docs/demo-bundle.js` file that gets generated in your PR).
- Unit test coverage added/updated.
- E2E (i.e. demos) test coverage added/updated.
  - ⚠️ Non-covered demos (look for `// TEST MANUALLY` comments [here](https://github.com/focus-trap/focus-trap/blob/master/docs/js/index.js)) that can't be fully tested in Cypress have been __manually__ verified.
- Typings added/updated.
- Changes do not break SSR:
  - Careful to test `typeof document/window !== 'undefined'` before using it in code that gets executed on load.
- README updated (API changes, instructions, etc.).
- Changes to dependencies explained.
- Changeset added (run `npm run changeset` locally to add one, and follow the prompts).
  - EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package bundle. For example, demo changes, tooling changes, test updates, or a new dev-only dependency to run tests more efficiently should not have a Changeset since it will not affect package consumers.

</details>

### CODE REVIEW

**Review by FloEdelmann — CHANGES_REQUESTED** [review]
Unfortunately, that doesn't solve the problem. Being able to specify a function that always returns `undefined` is not really more helpful than specifying `undefined` directly. Instead, we would need something like `FocusTargetValueOrFalse | (() => FocusTargetValueOrFalse | undefined) | undefined`.

FYI, the information I get with your changes when trying `initialFocus: () => someCondition ? someElement : undefined`:

```
Type '() => HTMLElement | undefined' is not assignable to type 'FocusTargetOrFalse | (() => undefined) | undefined'.
```

**Comment by stefcameron** [comment]
@FloEdelmann Thanks for checking it out. You're right, I was able to reproduce the error. I think the fix is simply changing the function type to `() => void`. See this playground where your test function works (code is at the bottom):

https://www.typescriptlang.org/play?#code/PTAEBcE8AcFMGdQDMBOB7AtqAFuc14AuEAcwEtxsBXAIwDoBjTYJNBq+AWnBQENoWbDtz4DoVADYTgARgAMANgBMAKBVQ4oAGJD4AFV4oSscADVeEqrFABeUAAk9AWQAyAUQmwMsAHbhQAD6gAMqmAOIeXr7+QfA8ZD4kANzqMNY67PqGxmYWVgDyKFoW8NZ2GRwGRibmltZBSCWwKSqgoMAAVB2tbR2gAIKgACL5TqA+aAAmsAA0oLygpZ4M4Ggoi-GJoAAUAO7YZAzYoLtkUqA01tC88KWTEGg9oH0ABpNC3n50AI5WKJDBWDLVYobYASheD2QCXulGsIzGE2mYLma3myCoPhWZDQPgg2F44CefRQJioKB8iAWCPGU1gdGJwFSmgqWWq-nKuiqOVqVkCO3BtgAfNoudkanlYGCWm1Ot02s8BsNRrTpnMFktYCs0XEUAkSDt9odjqdzpdQNdbrBYY8Fa93uxPuAfn8AUCtSDwZDVtCfLDsPCVUipXMXo0JKVvWhQLAAB7QCSHCgSSCgGGHQmwYnzPFoaDgThoKjgVHrBZITHY3H4wmgUngcmU9E04OgNFhpovBl2pkadJi9mFYoRsqizLciV1IdNfnbQU2EWsie5KdFJrStRtPugJxF0puABu0T0aAAQmg0J5eHi7NtYEe-IQd3vYIfovyT1Qjm+-GDhRcLyvHwUi3NJQAAaVgSAaDQQxJh-cAT3PS9YGvWwdnvaIn0g6DYJQeCH3AP8FwAlDrxldouggXgaBoGjPDbfMcSbeAqGgaA1nAa0LlTVhMhEfg6GeJkEi4lBGgYftx1EAxaPo2B8iY3FEAAbx6ABfNRRNgcTeEk0BFPAZjVKeSj5QVRVBgrLEjOrSha1NCQLmsBgLE8e4ukuVhSSo0o-X1ZBdChOFTMVcBxX8d0nVANjqz0oyD0JZjuwsjomQs3F+mxRKuIAfifecRQPNAyEmCjZS6UK+isytbLxez-Ec5zQFcqRuK6XgkDEqi+I4HAbmc3xFnfH0QossKIpjTxotivF4rIHLkqq9KFVxAAFNA4iyhLM3ynZiKKkqys3BU5SqpVrKreqCUas4nPNVr3LTDBvEmMhMxTeYup0-FrB4fgAHJEDiTM00QNjJkzG1muuDhrRSntTPW3g4b2wrQGK0ryrM86aps5ia1us0XLc7jOrE36IFEfrEEuIamAwBMTCBVNYbuHN7jIRAJlACRcWMFBztADBr14chEmAf72IC3r4AR3oVradbNvANaUdKNGDoxo7sbO8bqoxfG7Juk47uax7uLIF7rXerjPvJn64SpwHgfCriwZi6BIa46HzXmo8hbF3gEjmGhiwtPU0R9CGkq2ChEAAawmXZ3OMNskBOE3gypUlqLkmgGNOSgEjTcBECYPxg58HT4BmQO-QjnF1h9f2WeF0XxZISXRGgGXdHl4SkZ8ABVHw2dgTX-0x47TL11KLtqgmGtN4mWtJ+4HebgNnegGnBrxBmmbt1NMXHjeG65tssSzfW2iDkuRZ8MX9W7-he62WWB7SoeNriUfx8niRaeutKq3zxldQK6xphiQwAkAKZAM4UA9vATqf1ox+XuLLYK28sFS3OmiCYzoqrnQAJL+HgNgIsEh7j1kbOiaA6BYGlEJlfT6pJ4CXiPIgXE+k3KU0THEbiLwK7hQSDXF451DDWHklCUkkkFrWE-sQ2+eht7iBQBxZhaAM7F0QJfH0DDMJ+BjIYT6ssBK739klascUfBWyhudN6Fg0AkEQMvRo0w0xzQbkWZ0oAADqAY5qgCcXzA0HiEBeLmHCXOl8Fg0D1LADO0wJC8EgOdS44BdiwCGk7KxdV06UylhzIp1MorvkuH3TI8kv6KxagGBgCcADC14lyiDRqFFquJRHVxQEQAYKA+CQAADyOFcJEaKQRQgRGmtEIUpktZrUYVzWAwzp5ChAeZO0C8jbXQcmbB669ngdC8msWAvlfBvQ-kFUaAZzrxBIALKaURjGzRCahbK1ifC1KHkMD5O08oFS1sAk6FUtm9B2RA5eTVDltQ3t9Lef1qaX2mPk606oEWgBeLiP5aKuykIzi8WhFJWSQl2ANUoJZS4r3uiTOFxzN49SCgSWmOS8R+X8LcpFZBHk6XOuU15HE8Sos+XVJIbYYmnFKHMJBMK6VPU3u8-JBND6eC4nLZaP8Va4tFRPIFU8daz1AfPcBBTvLvJgXAuOiD-CXxQUgNBw0G5YLoo07B1gXgPIFpCAVRD9akPIZQyQNCyQUnocs5hy9cRsIQJwyJPCPVep0pCS+ssanKPnqoq45JNHWG0fiS++joyGMIpTF1sAAocqhGha89ifZUx5U831DxoyoRQCmL+oASEZwWEm9YzaIl6LxG84pIqAXMWiQGWJVILiJOSUCNJzkslsspmOhaXz8E6O3sU689x9i5O3XqXl-bZnGNTbodN-rb6eqPd6mlzUK0xMpq2ZeBJMFBQYU3d1O9nIBTRZMOut8o7b3YZIfw+anYvEpQAJVDT4UljE6oyozhXJAPLyTwwzds1Rl8CR+k8OsS+XRCFUQtpzLdHriXwd0PkHwOqAWwEhKh9DfACl5jqudbYwHKNwYQ2uxaNilI+D-KmkokAfkWSOFqZp15YMNhJboNGfanxjPcKemIIRwgTOiIsiNqz1mbPOqeVM0xGhgbmPu4JuDkVUl1f6RRZA+mRXU143651rMuzzm2fCP0mpyIrUeQKmQhL+IoMcXRiGCaQCLGvHw514BwAYAg1MCw3pIAdaSYxzafT+YUSwuBRkLBBY4KWGKzCOwjgkbfc1PMCvvSkLxXQ3Fm21jcl-c6AA5fIeg3BPkBHgAKEX2NL2jBVyMOw0TlkXsbWsVHEBjcY2Cc6TUS0jW3hViQrqE4IeG9WVAmBf1bDhpMdrt9+tGS2ENoTUIXiYlM2IyYkIuNlkNlCk2c2sV3aSQ9l4S3b5+YQGB1zTtTMowkP4S4BIDxNwkwqOrFhWR7SXBFacI5+RfbQ9Xe4QQ5zAqOhuCyc9tnGfeWZ8H6o8Q6XQOsOV+J0C7DxAgstNzqYiKrtzW089fVDtLm4mi3npgoBC2Fgt3DrvRaoLFxYiXkvzHc25LbzzooGPQCQPgL0kqPVTLlwLWCmc8zQDE+5NE6IF2sNz+YudWB3aEjoftsZeCM08HMCX7dUzkuMQsDiHEjwoCBudF4wy3oHiFFGOsWoAuKKCkzp23u0C+6Bl0vw74EgMEsNMDnxv84MW50JDoTheAJ2sKxXOTtwybb0gnJX74WXomriQJKAdr3hRoDCOMkIOHUtcnic0DCXHq5FkZLXxW7infnl1nrT5u1YvhxIBDl8FtPcm69gpy8PuL5RPcg4iBLoFKaoQ82RzLOlP4B7f9FP7g819ctg51hZ9mKayd0AOGd-TbxCLVMcRb9r3pUaBiTs8Fb44lso78t19Ry48M05WIjgWEYlpFc4eY+ZEgfprxUwW9TcGJs5zoS4ADRBYc2hy8ttEcnxkd2QQJTpjVtk-kydwAnwb0rAuwu1CVwxIwLMgkT9d4UV-l10fZAN54sEmoOgSNw95N6pownZssTY30R9nJvJpFRUlp9Y6kqNWRaN6MeC9VSIgJyCwUjMTMkkwcqUPNd5qx+Mvl70qNv1r9b5oUBpZZuJTlc5lVcR8DhpwA5NGxiDOkghSCeRJRUdShvCBROkLJgxWRrRTwkkzltoeDmIVNnA1MXkNNpltM-AQjQAtZfDJwCg1wRwCcKDwVFRqDDC6CeAGChJp9F9vMRDGx5sWDGNJ0PU3B4BXI4BIQi93czYD8+1HFuCBNcwKMZCpYhIX8pdzQ4YKwnImdXcPciQbDoxvJ9InY4Zm5owRYi90Rpgkt4ACYEhBFeB7h803I0BTgtg0JUJ4B0l-tF1fEhIOtDc-oTYmcptdkPZyAHwZVwBE9o1UwyM0xBi3BggmlQAOjlsBpDErQTtNULIEBWjYB1CcoEA9oYIyI8QggcIYI4IEIkJAJUJgIjVCi+hKiyjGNqj18SSXh1QWpEw3VfEdjPEy8WdT9HJei0VmdMgf1d15gpATjKY09Dgq8jFOVox3hecC0thtgyA6B6R7li0bguBKB0AqASBwtxDt5JCHIBp+TGlrQwQRjt9Itqwuhwoi94BzpDFJJphr4qJ48foXhjjdh8hix6TYAmkaSE4yV2CKBE9KUbsKS5hXIOB9Qt9axdsxDmoeUJhSQn9iiwM6D6j8UlDTJtSE4nSy5Sp4S+jMx4BkTcS0Ighdw4ZsSzw8z8TCdKCIVp9fSuTL40RySUAGCqSUy2xnSMz2S+pil99DcMkrhSRCJ0UYwHxM4hphF3S0yXSETsyU06jOwQsgkA8UzxyMzJz1VpysV-TRdDTGdEAuhIyzlJgqJJTpTO0mdvSZ1d8J1qUuyId5VdShJh5I0DSwyoQRF0AJBsCM5tguSjFM5jQ-wUyc5pEeTslDjWyGTD1T8S4K4AArN-G-SgLFRcsCzMtFfpBMoSWM8HeM2c6EhUB0pc6YN0gU3M1E-kQs-cQiHE1EnQnGW+EnUHczEfQUJqFot8pyLlavM9DOA-EuaHWAXYDiFAP1eeMhKXPvSYL8awTEbSP0ZrdLD0RARMDY1iy8RMLYRXDi1YEwntYWKYCwTtKskwP0hsho2kRYBgNi+9AkdiXwVw1bPwYICy1Ski7Qgk86TC2g9ckyxgv5VJSANxbeFGVYAQ9gxkjk4pYAhjKElRA0+ysuTi+KouA4a6KPapM3BK5ARhNefMckYMmw9U0tZePtbiMKjs6mZw75XCtoFJNJEhOxQrOfRTJ8FE1y8swk4YAwuMrFU494XYOgB0KgJ0Hyj4d8fdUvHBJk3eWnVuTtUYh0txaMOGMcSoZFbxNMLQdXFybpOMYSxGCyAap0PaIYEavwQzM7GXNDBgPODAvNITcuXENDEgckGRPbXQCxVw9A+SQyYyJHLkGSE3L6u6s6+eagsRSmEgPmOidi6mEGRpfUy+dYyJJBTRHY9Kn0ChKRSmFBbwDYSvbA9-MDMgJmLxEGa+bhZgt6qWFNFKxYR3K4MWYvL8cLG6SRYsNATgCq4ANmAKCDUQPRRAPvOAdtX4i8fCBIKGeYDAfmbkqYykcKMmyRWzcdM4n9Y-a8Q3KdM-CQUkA4lLEAxYINahcPVicHYHbeDWvlW+SpM4tmzgM+ISeizq8nExGAvY+W-SJqKHO-eKk4xnZPCkIrWGhOPg7ZK8K5A0H0VDGk+KmPAMVMD5cLf4YKamUqqkTlbebGv6K2GUpMiyKWYIcKRpPafoQZNJYZNpfgDZUFWikG5mFAWBauPRQY94oaDozE-CQclPGdAAIhb0gXJXwm7s7uMWhTNilqb3nlTu-WrljE5R7maxcxwP5zWEFwwqdvio4peD0H6FPHaKgk7QfMeKLTbF9z1HAqRU80h14GhzRGmJi1mKhCWsMHpxBKggWqTx4EvHOjbrwkv2vp5XMKSpwIgugDmHNTjEdyZiEn6AjHQRyRn3gBwlPErwHsmC9C3NcK5hwjt1Qb2gxN-uLOQlcrctvj+UtUbv+PBoUTxB-rgmHttR7r7q21QaHqFJYSanHpvknomvCrVN7PvBxDKrfgXqSOB2Xp8yFw6poPfsg2CHsBIS0D0AAGpt7d7X7xNzpD7NyfRbTBk2zcDL7YAocv077JcH7o5mFn7eSOj37Xyv7b5aGO6n5ocG898wtgGL7QHIEYwHcnd6QBhYHhoPUsGoIcG4J0GwzMHEGoJkHGlcHsIoJ26CJjwSzqKNITptwYjETvrlJ0I1oBThkcnKQ5gAZMpdUAZ+RSmfBf5wAsnMwKmggAYpNGkWlqNpJAYq7QJNA1Y4YinEA7B8nGlCm7qSnkY4YGnQAqmamenSgAZOmIAwJ-51YFI7q8mCm+nRmR4x5lmJmpmVYlnxmq6ehtJdJ9IVyVm6pEAdrLlEBBmE5hnLnNnzndnlY4hnnKnmmZMfAPCFNMg5nQA1ILIVCmqtC8TyDNIVATmJIpIVrT9AW8KQDmrSyQ6LRlnJgkXUSUW0UvzdU+ni7cW7qwQSC-r+AaKzCuJthyWLmfqnxzm+miXlr9BRAaLx5thx48WnwZnqXlIGWK7oAaLT5lnthBXem7q9oDnSh6XiX2n+XTIY4uImlukq4dJUiy5tg2cxEUBVX+lVNVX+QUiXNYhNgDQggS6hlRkEi9WpktNDWNg9REghReWSXZW2gIWQB3WPXPWvXvWfXfW-X-WA3A2g3A2VAQBn9AS9BQ3g3o2Y3Y24343-W1AK44gk83oCk7B6iUhk3wM7qnw+n0J4W2hZ9WR9USIK402CZcoQkTr-AnwMcHsVBNIgA

**Review by FloEdelmann — APPROVED** [review]
Indeed, that seems to work fine :slightly_smiling_face: 
Thanks for fixing this so quickly!

**Comment by stefcameron** [comment]
I will push this out next early next week.

**Comment by stefcameron** [comment]
Published in v7.5.3

**Pull request merged**
