### PR TITLE
Update demo link in readme

### PR DESCRIPTION
**Pull request by scottblinch**
It looks like that with the transition to a Github org, the demo link was missed in the readme. Lemme know if I messed up the formatting in this PR.

###  Features and Bug Fixes

- [x] README updated (API changes, instructions, etc.).

### Tooling

- [x] README instructions updated.

### CODE REVIEW

**Review by stefcameron — APPROVED** [review]
Good catch, thank you!

**Comment by stefcameron** [comment]
@all-contributors add @scottblinch for docs

**Comment by scottblinch** [comment]
No prob! This one is still referencing the old URL but I believe that's a setting somewhere in the Github repo:

image

**Comment by stefcameron** [comment]
> No prob! This one is still referencing the old URL but I believe that's a setting somewhere in the Github repo:

Oh, yes, you need admin privileges for that. It's fixed now!

**Pull request merged**
