### PR TITLE
Fix bug with negative tabindex NOT last in container

### LINKED ISSUE #611: Focusing an isFocusable, yet not isTabbable element results in focusing the first element in the container
Hi there!

We are using skip links in our modal which leverages the focus-trap. It seems that the way #565 was fixed broke our skip link implementation :)

It basically looks like this:
```
<hr id="skip-link-target-top"  />         # visibility: hidden
<a href="#skip-link-target-bottom" />
...
<hr id="skip-link-target-bottom" />       # visibility: hidden
<a href="#skip-link-target-top" />
```

When the user clicks (tabs I should say - it's actually hidden as well) on the skip link, the corresponding target becomes visible and gets focused.

I created a codesandbox to showcase the behaviour: https://codesandbox.io/s/focus-trap-skip-links-eyz0g
It works with version 6.7.1 but not with version 6.7.2.

Basically https://github.com/focus-trap/focus-trap/blob/1700055ed7629aecbd5b8fb73cd93dc0f248cffc/index.js#L414 leads to `lastOfGroupIndex` to be set to `containerIndex` which a few lines later on sets the `destinationNode` to `destinationGroup.firstTabbableNode`.

I was wondering if we should try a different approach to improve our UX for both sighted and blind users, but on the otherhand, the underlying assumption which is made on line 418ff doesn't seem right to me? :thinking: From a userperspective I would expect the tabflow to continue from the focused element.

What do you think?

Best regards!

### PR DESCRIPTION
**Pull request by stefcameron**
Fixes #611

negative-tabindex-middle

<details>
<summary>PR Checklist</summary>
<br/>

__Please leave this checklist in your PR.__

- Source changes maintain stated browser compatibility.
- Includes updated docs demo bundle if source/docs code was changed (run `yarn demo-bundle` in your branch and include the `/docs/demo-bundle.js` file that gets generated in your PR).
- Issue being fixed is referenced.
- Unit test coverage added/updated.
- E2E (i.e. demos) test coverage added/updated.
  - ⚠️ Non-covered demos (look for `IS_CYPRESS_ENV === ''` [here](https://github.com/focus-trap/focus-trap/blob/master/docs/js/index.js), as well as `in-open-shadow-dom.js` and `negative-tabindex.js` that can't be fully tested in Cypress) __manually__ verified.
- Typings added/updated.
- Changes do not break SSR:
  - Careful to test `typeof document/window !== 'undefined'` before using it in code that gets executed on load.
- README updated (API changes, instructions, etc.).
- Changes to dependencies explained.
- Changeset added (run `yarn changeset` locally to add one, and follow the prompts).
  - EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package bundle. For example, tooling changes, test updates, or a new dev-only dependency to run tests more efficiently should not have a Changeset since it will not affect package consumers.

</details>

### CODE REVIEW

**Comment by stefcameron** [comment]
There's a lint error in here on purpose because this needs further testing. It also needs a Changeset.

**Comment by stefcameron** [comment]
@skriems Please have a look... 🙂

**Comment by skriems** [comment]
Hey @stefcameron, that looks pretty good to me!

I haven't tested the solution really but since all of this is done inside `updateTabbableNodes` it should work regardless if the element got `tabindex=-1` via javascript or not. _brilliant_ :tada: :smile: 

Regarding the positive tabindex values... that's much much harder of a problem.... :thinking: I'll definately think about it!

Thanks for looking into that and your time!

**Comment by stefcameron** [comment]
> Hey @stefcameron, that looks pretty good to me!
> 
> I haven't tested the solution really but since all of this is done inside `updateTabbableNodes` it should work regardless if the element got `tabindex=-1` via javascript or not. _brilliant_ 🎉 😄

Glad to know it's looking good to you! You definitely inspired the fix.
 
> Regarding the positive tabindex values... that's much much harder of a problem.... 🤔 I'll definately think about it!

I'm concerned that the fix here won't work in the case of positive tabindex. We already have an outstanding issue with those on #375. But I guess whether this fix goes in or not, positive tabindex would still be broken because moving the focus to the first tabbable node in the container would be just as wrong as miscalculating the tab order in the negative tab index case.

> Thanks for looking into that and your time!

My pleasure.

**Comment by stefcameron** [comment]
I've come to the conclusion that since positive tabindex is already broken (see #375), this fix isn't going to make any matters worse, so we might as well go with it.

**Pull request merged**
