### PR TITLE
demo site improvements

### PR DESCRIPTION
**Pull request by Dan503**
- Installing cross-env for windows support
- Fixing aria-label [accessibility failure](https://www.w3.org/WAI/WCAG21/Understanding/label-in-name)
- Adding links in HTML to source code
-  Updating container class handling to use `container.classList.add/remove('is-active')`

<details>
<summary>PR Checklist</summary>
<br/>

__Please leave this checklist in your PR.__

- Source changes maintain stated browser compatibility.
- Issue being fixed is referenced.
- Unit test coverage added/updated.
- E2E test coverage added/updated.
- Typings added/updated.
- README updated (API changes, instructions, etc.).
- Changes to dependencies explained.
- Changeset added (run `yarn changeset` locally to add one, and follow the prompts).
  - EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package bundle. For example, tooling changes, test updates, or a new dev-only dependency to run tests more efficiently should not have a Changeset since it will not affect package consumers.

</details>

### CODE REVIEW

**Comment by Dan503** [comment]
Oh I forgot, I should add the `.classList` change to this PR as well.

**Review by stefcameron — CHANGES_REQUESTED** [review]
Thanks for moving this stuff to a different PR! You're missing the lock file changes for `cross-env`, and CI failed, please see what that was about.

**Comment by Dan503** [comment]
lock file fixed now

**Review by stefcameron — APPROVED** [review]
Looks good! And thanks for that extra bit of attention to detail with `<span aria-hidden="true">&gt;&gt;</span>` to hide the visual indicators from the screen readers.

**Comment by stefcameron** [comment]
@all-contributors add @Dan503 for docs, tool

**Comment by stefcameron** [comment]
@all-contributors add @Dan503 for a11y

**Pull request merged**
