### PR TITLE
Support elements with positive tabindex attributes in single-container traps

### LINKED ISSUE #375: focus-trap stuck on elements with positive tabIndex
Hi!

It seems elements with positive tabIndex break tab/shift+tab navigation. When such elements receive focus moving forward become unavailable. While moving backward returning to that element is also unavailable, focus cycle inside container is not working.

Here's a repro example - https://codesandbox.io/s/focus-trap-tab-index-u1fxu

**Current behavior**
1. Activate the trap -> focus moves to button with tabIndex="1"
2. Press Tab -> nothing happens

**Expected behavior**
1. Activate the trap -> focus moves to button with tabIndex="1"
2. Press Tab -> focus moves to button with no tabIndex

### PR DESCRIPTION
**Pull request by stefcameron**
Fixes #375

ALL existing cypress tests are passing.

The goal is to take the least invasive approach when it comes to enforcing tab order. Let the browser do as much of the work as possible, and only interject when it doesn't do what we expect it to (which is the general theme of focus-trap).

Here's the working demo, including negative tabindex edge case support:

focus-trap-positive-tabindex

DONE:

- [x] artificially limit the trap to a single container if at least one positive tabindex node is discovered (check for it in `updateTabbableNodes()`
    - `if >1 container && >0 positive tabindex nodes found, then throw Error("trap not supported")`
- [x] handle edge case where MRU focused node had negative tabindex
    - in this case, the browser apparently sets focus on the next element in DOM order, not tabindex order
    - or just ignore this as a rare edge case
- [x] get rid of DEBUG comments
- [x] will need to share logic from tabbable about determining tabindex somehow
  - Keep this Tabbable commit except for the multi-container-related typing updates: https://github.com/focus-trap/tabbable/commit/5b753b6f8d190a60ff636553a83d0eaae8d58492
- [x] check manually tested examples
- [x] see if a cypress test can be added for the new positive-tabindex example
- [x] add changeset

<details>
<summary>PR Checklist</summary>
<br/>

__Please leave this checklist in your PR.__

- Source changes maintain stated browser compatibility.
- Includes updated docs demo bundle if source/docs code was changed (run `npm run demo-bundle` in your branch and include the `/docs/demo-bundle.js` file that gets generated in your PR).
- Issue being fixed is referenced.
- Unit test coverage added/updated.
- E2E (i.e. demos) test coverage added/updated.
  - ⚠️ Non-covered demos (look for `// TEST MANUALLY` comments [here](https://github.com/focus-trap/focus-trap/blob/master/docs/js/index.js)) that can't be fully tested in Cypress have been __manually__ verified.
- Typings added/updated.
- Changes do not break SSR:
  - Careful to test `typeof document/window !== 'undefined'` before using it in code that gets executed on load.
- README updated (API changes, instructions, etc.).
- Changes to dependencies explained.
- Changeset added (run `npm run changeset` locally to add one, and follow the prompts).
  - EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package bundle. For example, demo changes, tooling changes, test updates, or a new dev-only dependency to run tests more efficiently should not have a Changeset since it will not affect package consumers.

</details>

### CODE REVIEW

**Comment by DaviDevMod** [comment]
I made a few adjustments in [my fork](https://github.com/DaviDevMod/focus-trap-not-mine/tree/positive-tabindex).
I'm going to reproduce the changes here.

By the way, I noticed this:

https://github.com/focus-trap/focus-trap/blob/f22e3611a6eebbf1245f34e0a37a86250a5875fc/index.js#L72

Which can be removed, since *tabbable* doesn't support IE anymore.
But this change doesn't belong to this PR.

**Comment by DaviDevMod** [comment]
@stefcameron It looks like I can't review arbitrary lines, eg, I can't review line 516 of index.js to make [this suggestion](https://github.com/DaviDevMod/focus-trap-not-mine/commit/b5a5f191a02f30e20026bef454076b9942e08a2e).

So either I open another PR against `focus-trap/positive-tabindex` or you pull the changes from my fork.

**Comment by stefcameron** [comment]
@DaviDevMod I think it's because using `suggestion` in a comment equates to writing directly to a branch. Looks like you made 3 commits in your fork. Might be better to make a PR into this `positive-tabindex` branch. I should then be able to merge that into this branch/PR, and then the whole into `master`.

Unless it's just that one suggestion you're wanting to make, in which case I can easily add that myself, but just wondering what's going on there.

**Comment by stefcameron** [comment]
@all-contributors add @DaviDevMod for code, bug

**Pull request merged**
