### PR TITLE
Add initialFocusOnActivate option to control initial focus when activating trap

### PR DESCRIPTION
**Pull request by mruzekw**
Addresses #113

There may be cases where we don't want to focus the first tabbable element when a focus trap activates.

Examples:
- Modals/dialogs
- On mobile devices where "tabbing" doesn't make sense without a connected Bluetooth keyboard

This gives us the option to initially focus the first tabbable element or not.

- [x] Source changes maintain stated browser compatibility.
- [x] Includes updated `/docs/demo-bundle.js` if source or docs code was changed.
- [x] Issue being fixed is referenced.
- N/A Unit test coverage added/updated.
- [x] E2E test coverage added/updated.
- [x] Typings added/updated.
- [x] README updated (API changes, instructions, etc.).
- N/A Changes to dependencies explained.
- [x] Changeset added (run `yarn changeset` locally to add one, and follow the prompts).
  - EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package bundle. For example, tooling changes, test updates, or a new dev-only dependency to run tests more efficiently should not have a Changeset since it will not affect package consumers.

### CODE REVIEW

**Review by stefcameron — COMMENTED** [review]
@mruzekw Wow, thank you for such a thorough update! You covered all the Ts and dotted all the Is. 😄 

I'm wondering, though, if we really need to add yet another configuration option (there are so many now), especially since this new one basically disables the `initialFocus` option.

Adding a new option, `initialFocusOnActivate`, gives me the impression it's strictly for the first activation, but really, it's disabling all cases where we use the `initialFocus` option.

The only exception is `tryFocus(state.mostRecentlyFocusedNode || getInitialFocusNode());` in the `checkFocusIn()` handler, when focus escapes, and we use it as a fallback if `state.mostRecentlyFocusedNode` isn't set for some reason. But then, I don't think we need the fallback there if you're disabling the `initialFocus` behavior, because already, you're starting with a focus trap that doesn't contain its own focus... It's now up to the developer to set focus to some node in the trap on their own.

`state.mostRecentlyFocusedNode` should end-up getting assigned when the developer sets focus to a node inside one of the trap containers (hopefully -- that would be one special case to test for).

Why not support `false` as a valid value for the `initialFocus` option instead? If it's `=== false`, then we just ignore it.

That would mean the internal `getInitialFocusNode()` function would first check
```javascript
if (config.initialFocus === false) {
  return false;
}
...
```

And then the internal `tryFocus(node)` function would simply do nothing if `node === false` (which should also terminate the recursive stack of the function even if `node` isn't initially false, and we fall into line 210 `tryFocus(getInitialFocusNode())`).

Then we'd have one less option to manage, and I think the overall changes to `index.js` would also be somewhat less than what they are now.

What do you think about that?

**Comment by mruzekw** [comment]
Thanks for your thorough feedback @stefcameron :) 

That all makes sense and sounds good to me. I'll make that change today.

Would you like me to test `state.mostRecentlyFocusedNode` gets set as well?

**Comment by stefcameron** [comment]
> Thanks for your thorough feedback @stefcameron :)
> 
> That all makes sense and sounds good to me. I'll make that change today.

My pleasure, looking forward to it when you have time!

> Would you like me to test `state.mostRecentlyFocusedNode` gets set as well?

Yes, that would be good to test.

**Comment by mruzekw** [comment]
@stefcameron Okay, all those changes should be up! Let me know if I overlooked anything. Thanks 🙏

**Comment by stefcameron** [comment]
> @stefcameron Okay, all those changes should be up! Let me know if I overlooked anything. Thanks 🙏

👀

**Review by stefcameron — APPROVED** [review]
Thank you for the update! This looks great. A nice, simple addition to cover another use case.

**Comment by mruzekw** [comment]
Awesome! Thanks for reviewing. It doesn't look like I have merge access. Is there someone we can ping who does? Thanks.

**Comment by stefcameron** [comment]
My pleasure! I will merge it, just got distracted with work. 😄

**Comment by mruzekw** [comment]
Thanks! It's no problem.

**Comment by stefcameron** [comment]
This is being published in 6.6.0 right now.

**Pull request merged**
